jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        node_13_x:
          node_version: 13.x
        node_12_x:
          node_version: 12.x
        node_10_x:
          node_version: 10.x
      maxParallel: 6

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js

      - bash: yarn install
        displayName: Install dependencies

      - bash: yarn build
        displayName: Lint and Build
