language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

install:
  - travis_retry npm install

before_script:
  - npm run lint
script:
  - npm run build
after_script:
  - npm run test:ci

notifications:
  email:
    on_success: never
    on_failure: always
