language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

install:
  - travis_retry npm install

script:
  - npm run lint
  - npm run build
  - npm run test:ci
  - echo $(cat lcov.info)

notifications:
  email:
    on_success: never
    on_failure: always
