language: node_js

node_js:
  - "12"
  - "11.0.0"
  - "10"

branches:
  only:
    - master

install:
  - travis_retry npm install

before_script:
  - npm run lint
script:
  - npm run build
after_success:
  - npm run test:coveralls

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release

notifications:
  email:
    on_success: never
    on_failure: always
